namespace HotReloading.Syntax.Statements
{
    public enum BinaryOperand
    {
        Assign,
        Add,
        AddAssign,
        Sub,
        SubAssign,
        Multiply,
        MultiplyAssign,
        Divide,
        DivideAssign,
        Modulo,
        ModuloAssign,
        Equal,
        NotEqual,
        And,
        Or,
        GreaterThan,
        GreaterThanEqual,
        LessThan,
        LessThanEqual,
        BitwiseAnd,
        BitwiseAndAssign,
        BitwiseOr,
        BitwiseOrAssign,
        Xor,
        XorAssign,
        LeftShift,
        LeftShiftAssign,
        RightShift,
        RightShiftAssign,
        Coalesce
    }
}
